version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/src/otel-collector-builder"
  schedule:
    interval: "weekly"

# Ignoring this path since we'd like to manage its dependencies through the config.yaml
# - package-ecosystem: "gomod"
#   directory: "/src/otel-collector"
#   schedule:
#     interval: "weekly"

- package-ecosystem: "gomod"
  directory: "/src/integration"
  schedule:
    interval: "weekly"

- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "weekly"
