dist:
  module: code.cloudfoundry.org/otel-collector-release/src/otel-collector
  name: otelcol-cf
  description: OpenTelemetry Collector for CloudFoundry
  otelcol_version: 0.131.0
  output_path: ../otel-collector
  version: 0.11.4
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.131.0
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.131.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.131.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.131.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.131.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/splunkhecexporter v0.131.0
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.131.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.131.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.131.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.131.0
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.131.0
providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.37.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.37.0
extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.131.0