dist:
  module: code.cloudfoundry.org/otel-collector-release/src/otel-collector
  name: cf-otel-collector
  description: Cloud Foundry OpenTelemetry Collector
  otelcol_version: 0.104.0
  output_path: ../otel-collector
  version: 0.6.0
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.104.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.104.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.104.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.104.0
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.104.0
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.104.0
