dist:
  module: code.cloudfoundry.org/otel-collector-release/src/otel-collector
  name: cf-otel-collector
  description: Cloud Foundry OpenTelemetry Collector
  output_path: ../otel-collector
  version: 0.11.2
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.117.0
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.117.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.117.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.117.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.117.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/splunkhecexporter v0.117.0
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.117.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.117.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.117.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.117.0
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.117.0
providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.23.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.23.0
extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.117.0
