package acceptance_test

import (
	"fmt"
	"os/exec"
	"time"

	"github.com/onsi/gomega/gbytes"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"github.com/onsi/gomega/gexec"
)

var _ = Describe("OpAMP (Open Agent Management Protocol) - Simplified Implementation", func() {

	Context("When OpAMP is enabled (opamp.enabled=true) - Dual Process Mode", func() {
		It("should show OpAMP extension in the collector configuration", func() {
			Eventually(func() error {
				boshCmd := exec.Command("bosh", "ssh", "diego-cell/0", "-c", "sudo cat /var/vcap/jobs/otel-collector/config/config.yml | grep -A 10 'extensions:' | grep -q 'opamp:'")
				boshCmd.Stdout = GinkgoWriter
				boshCmd.Stderr = GinkgoWriter
				return boshCmd.Run()
			}, 60*time.Second, 5*time.Second).Should(Succeed(), "OpAMP extension should be present in collector configuration")
		})

		It("should have OpAMP extension loaded in the collector process", func() {
			Eventually(func(g Gomega) *gbytes.Buffer {
				boshCmd := exec.Command("bosh", "ssh", "diego-cell/0", "-c", "sudo journalctl -u vcap.otel-collector --no-pager -n 100")
				session, err := gexec.Start(boshCmd, GinkgoWriter, GinkgoWriter)
				Expect(err).ShouldNot(HaveOccurred())
				return session.Wait(60 * time.Second).Out
			}, 2*time.Minute).Should(gbytes.Say("opamp.*extension.*started"), "OpAMP extension should be started in collector logs")
		})

		It("should attempt to connect to OpAMP server", func() {
			Eventually(func(g Gomega) *gbytes.Buffer {
				boshCmd := exec.Command("bosh", "ssh", "diego-cell/0", "-c", "sudo journalctl -u vcap.otel-collector --no-pager -n 200")
				session, err := gexec.Start(boshCmd, GinkgoWriter, GinkgoWriter)
				Expect(err).ShouldNot(HaveOccurred())
				return session.Wait(60 * time.Second).Out
			}, 2*time.Minute).Should(gbytes.Say("opamp.*connecting|opamp.*connection"), "OpAMP extension should attempt server connection")
		})

		It("should have health check endpoint responding", func() {
			Eventually(func() error {
				boshCmd := exec.Command("bosh", "ssh", "diego-cell/0", "-c", "curl -f http://localhost:13133/")
				boshCmd.Stdout = GinkgoWriter
				boshCmd.Stderr = GinkgoWriter
				return boshCmd.Run()
			}, 60*time.Second, 5*time.Second).Should(Succeed(), "Health check endpoint should be accessible")
		})

		It("should have both collector and supervisor processes running", func() {
			Eventually(func(g Gomega) *gbytes.Buffer {
				boshCmd := exec.Command("bosh", "ssh", "diego-cell/0", "-c", "sudo ps aux | grep -E '(otelcol-cf|opampsupervisor)' | grep -v grep")
				session, err := gexec.Start(boshCmd, GinkgoWriter, GinkgoWriter)
				Expect(err).ShouldNot(HaveOccurred())
				return session.Wait(30 * time.Second).Out
			}, 60*time.Second).Should(gbytes.Say("otelcol-cf.*opampsupervisor|opampsupervisor.*otelcol-cf"), "Both collector and supervisor processes should be running")
		})

		It("should use the wrapper script for process management", func() {
			Eventually(func(g Gomega) *gbytes.Buffer {
				boshCmd := exec.Command("bosh", "ssh", "diego-cell/0", "-c", "sudo cat /var/vcap/jobs/otel-collector/bin/bpm.yml | grep executable")
				session, err := gexec.Start(boshCmd, GinkgoWriter, GinkgoWriter)
				Expect(err).ShouldNot(HaveOccurred())
				return session.Wait(30 * time.Second).Out
			}, 60*time.Second).Should(gbytes.Say("otel-wrapper.sh"), "BPM should use the wrapper script")
		})
	})

	Context("When OpAMP supervisor is running (dual-process mode)", func() {
		It("should have OpAMP supervisor binary present", func() {
			Eventually(func() error {
				boshCmd := exec.Command("bosh", "ssh", "diego-cell/0", "-c", "test -f /var/vcap/packages/opamp-supervisor/opampsupervisor")
				boshCmd.Stdout = GinkgoWriter
				boshCmd.Stderr = GinkgoWriter
				return boshCmd.Run()
			}, 30*time.Second, 5*time.Second).Should(Succeed(), "OpAMP supervisor binary should exist")
		})

		It("should have OpAMP supervisor configuration file", func() {
			Eventually(func() error {
				boshCmd := exec.Command("bosh", "ssh", "diego-cell/0", "-c", "test -f /var/vcap/jobs/otel-collector/config/opamp-supervisor.yml")
				boshCmd.Stdout = GinkgoWriter
				boshCmd.Stderr = GinkgoWriter
				return boshCmd.Run()
			}, 30*time.Second, 5*time.Second).Should(Succeed(), "OpAMP supervisor config should exist (generated by wrapper)")
		})

		It("should show OpAMP supervisor process running when enabled", func() {
			Eventually(func(g Gomega) *gbytes.Buffer {
				boshCmd := exec.Command("bosh", "ssh", "diego-cell/0", "-c", "sudo ps aux | grep opampsupervisor")
				session, err := gexec.Start(boshCmd, GinkgoWriter, GinkgoWriter)
				Expect(err).ShouldNot(HaveOccurred())
				return session.Wait(30 * time.Second).Out
			}, 60*time.Second).Should(gbytes.Say("opampsupervisor"), "OpAMP supervisor process should be running")
		})

		It("should have OpAMP supervisor logs showing startup", func() {
			Eventually(func(g Gomega) *gbytes.Buffer {
				boshCmd := exec.Command("bosh", "ssh", "diego-cell/0", "-c", "sudo journalctl -u vcap.otel-collector --no-pager -n 100")
				session, err := gexec.Start(boshCmd, GinkgoWriter, GinkgoWriter)
				Expect(err).ShouldNot(HaveOccurred())
				return session.Wait(60 * time.Second).Out
			}, 2*time.Minute).Should(gbytes.Say("Starting dual-process mode|Starting OpAMP Supervisor"), "OpAMP supervisor should show startup logs in collector job")
		})

		It("should create OpAMP storage directory", func() {
			Eventually(func() error {
				boshCmd := exec.Command("bosh", "ssh", "diego-cell/0", "-c", "test -d /var/vcap/data/otel-collector/opamp-storage")
				boshCmd.Stdout = GinkgoWriter
				boshCmd.Stderr = GinkgoWriter
				return boshCmd.Run()
			}, 60*time.Second, 5*time.Second).Should(Succeed(), "OpAMP storage directory should exist")
		})
	})

	Context("When OpAMP is disabled (opamp.enabled=false) - Single Process Mode", func() {
		It("should not have OpAMP extension in collector configuration", func() {
			Eventually(func() error {
				// This test assumes a deployment where OpAMP is disabled
				boshCmd := exec.Command("bosh", "ssh", "router/0", "-c", "sudo cat /var/vcap/jobs/otel-collector/config/config.yml | grep -v '^#' | grep -q 'opamp:' && exit 1 || exit 0")
				boshCmd.Stdout = GinkgoWriter
				boshCmd.Stderr = GinkgoWriter
				return boshCmd.Run()
			}, 30*time.Second, 5*time.Second).Should(Succeed(), "OpAMP extension should not be present when disabled")
		})

		It("should not have OpAMP supervisor process running", func() {
			Eventually(func() error {
				// Check that no opamp supervisor process is running
				boshCmd := exec.Command("bosh", "ssh", "router/0", "-c", "sudo ps aux | grep opampsupervisor | grep -v grep && exit 1 || exit 0")
				boshCmd.Stdout = GinkgoWriter
				boshCmd.Stderr = GinkgoWriter
				return boshCmd.Run()
			}, 30*time.Second, 5*time.Second).Should(Succeed(), "OpAMP supervisor should not be running when disabled")
		})

		It("should only have collector process running", func() {
			Eventually(func(g Gomega) *gbytes.Buffer {
				boshCmd := exec.Command("bosh", "ssh", "router/0", "-c", "sudo ps aux | grep otelcol-cf | grep -v grep")
				session, err := gexec.Start(boshCmd, GinkgoWriter, GinkgoWriter)
				Expect(err).ShouldNot(HaveOccurred())
				return session.Wait(30 * time.Second).Out
			}, 60*time.Second).Should(gbytes.Say("otelcol-cf"), "Only collector process should be running when OpAMP is disabled")
		})

		It("should show single-process mode in logs", func() {
			Eventually(func(g Gomega) *gbytes.Buffer {
				boshCmd := exec.Command("bosh", "ssh", "router/0", "-c", "sudo journalctl -u vcap.otel-collector --no-pager -n 50")
				session, err := gexec.Start(boshCmd, GinkgoWriter, GinkgoWriter)
				Expect(err).ShouldNot(HaveOccurred())
				return session.Wait(60 * time.Second).Out
			}, 2*time.Minute).Should(gbytes.Say("Starting OpenTelemetry Collector \\(no OpAMP\\)"), "Should show single-process mode startup message")
		})
	})

	Context("Health Check Extension", func() {
		It("should have health check extension available on all VMs", func() {
			vmTypes := []string{"diego-cell/0", "router/0"}

			for _, vm := range vmTypes {
				vm := vm // capture loop variable
				It(fmt.Sprintf("should respond to health check on %s", vm), func() {
					Eventually(func() error {
						boshCmd := exec.Command("bosh", "ssh", vm, "-c", "curl -f -s http://localhost:13133/ | grep -q 'Server available'")
						boshCmd.Stdout = GinkgoWriter
						boshCmd.Stderr = GinkgoWriter
						return boshCmd.Run()
					}, 60*time.Second, 5*time.Second).Should(Succeed(), fmt.Sprintf("Health check should work on %s", vm))
				})
			}
		})

		It("should show health check extension in collector logs", func() {
			Eventually(func(g Gomega) *gbytes.Buffer {
				boshCmd := exec.Command("bosh", "ssh", "diego-cell/0", "-c", "sudo journalctl -u vcap.otel-collector --no-pager -n 100")
				session, err := gexec.Start(boshCmd, GinkgoWriter, GinkgoWriter)
				Expect(err).ShouldNot(HaveOccurred())
				return session.Wait(60 * time.Second).Out
			}, 2*time.Minute).Should(gbytes.Say("health_check.*extension.*started"), "Health check extension should be started")
		})
	})

	Context("OpAMP Configuration Validation", func() {
		It("should validate OpAMP server endpoint configuration", func() {
			Eventually(func(g Gomega) *gbytes.Buffer {
				boshCmd := exec.Command("bosh", "ssh", "diego-cell/0", "-c", "sudo cat /var/vcap/jobs/otel-collector/config/config.yml")
				session, err := gexec.Start(boshCmd, GinkgoWriter, GinkgoWriter)
				Expect(err).ShouldNot(HaveOccurred())
				return session.Wait(30 * time.Second).Out
			}, 60*time.Second).Should(gbytes.Say("endpoint:.*ws://"), "OpAMP configuration should have valid WebSocket endpoint")
		})

		It("should have proper agent description in OpAMP configuration", func() {
			Eventually(func(g Gomega) *gbytes.Buffer {
				boshCmd := exec.Command("bosh", "ssh", "diego-cell/0", "-c", "sudo cat /var/vcap/jobs/otel-collector/config/config.yml")
				session, err := gexec.Start(boshCmd, GinkgoWriter, GinkgoWriter)
				Expect(err).ShouldNot(HaveOccurred())
				return session.Wait(30 * time.Second).Out
			}, 60*time.Second).Should(gbytes.Say("agent_description:"), "OpAMP configuration should have agent description")
		})

		It("should have OpAMP extension in service extensions list", func() {
			Eventually(func(g Gomega) *gbytes.Buffer {
				boshCmd := exec.Command("bosh", "ssh", "diego-cell/0", "-c", "sudo cat /var/vcap/jobs/otel-collector/config/config.yml | grep -A 20 'service:' | grep -A 10 'extensions:'")
				session, err := gexec.Start(boshCmd, GinkgoWriter, GinkgoWriter)
				Expect(err).ShouldNot(HaveOccurred())
				return session.Wait(30 * time.Second).Out
			}, 60*time.Second).Should(gbytes.Say("opamp"), "OpAMP should be listed in service extensions")
		})
	})

	Context("OpAMP Metrics and Monitoring", func() {
		It("should expose OpAMP metrics through the collector", func() {
			Eventually(func() error {
				boshCmd := exec.Command("bosh", "ssh", "diego-cell/0", "-c", "curl -s http://localhost:8888/metrics | grep -q 'otelcol_opamp'")
				boshCmd.Stdout = GinkgoWriter
				boshCmd.Stderr = GinkgoWriter
				return boshCmd.Run()
			}, 60*time.Second, 5*time.Second).Should(Succeed(), "OpAMP metrics should be available")
		})

		It("should show OpAMP connection status in metrics", func() {
			Eventually(func(g Gomega) *gbytes.Buffer {
				boshCmd := exec.Command("bosh", "ssh", "diego-cell/0", "-c", "curl -s http://localhost:8888/metrics")
				session, err := gexec.Start(boshCmd, GinkgoWriter, GinkgoWriter)
				Expect(err).ShouldNot(HaveOccurred())
				return session.Wait(30 * time.Second).Out
			}, 60*time.Second).Should(gbytes.Say("otelcol_opamp.*connection"), "OpAMP connection metrics should be present")
		})
	})

	Context("Windows Support", func() {
		It("should have OpAMP extension working on Windows cells", func() {
			Eventually(func(g Gomega) *gbytes.Buffer {
				boshCmd := exec.Command("bosh", "ssh", "windows2019-cell/0", "-c", "powershell -Command \"Get-Content C:\\var\\vcap\\jobs\\otel-collector\\config\\config.yml | Select-String 'opamp'\"")
				session, err := gexec.Start(boshCmd, GinkgoWriter, GinkgoWriter)
				Expect(err).ShouldNot(HaveOccurred())
				return session.Wait(60 * time.Second).Out
			}, 2*time.Minute).Should(gbytes.Say("opamp"), "OpAMP should be configured on Windows cells")
		})

		It("should have health check working on Windows cells", func() {
			Eventually(func() error {
				boshCmd := exec.Command("bosh", "ssh", "windows2019-cell/0", "-c", "powershell -Command \"Invoke-WebRequest -Uri http://localhost:13133/ -UseBasicParsing\"")
				boshCmd.Stdout = GinkgoWriter
				boshCmd.Stderr = GinkgoWriter
				return boshCmd.Run()
			}, 60*time.Second, 5*time.Second).Should(Succeed(), "Health check should work on Windows")
		})
	})
})
