name: scripts

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  spec-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - run: ./scripts/subtests/spec-test
