dist:
  module: code.cloudfoundry.org/otel-collector-release/src/otel-collector
  name: cf-otel-collector
  description: Cloud Foundry OpenTelemetry Collector
  otelcol_version: 0.91.0
  output_path: otel-collector
  version: 0.4.0
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.91.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.91.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.91.0
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.91.0
replaces:
  - golang.org/x/net => golang.org/x/net v0.24.0
